title: Victor Wissink
description: Victor Wissink; Lead QA Engineer at Wire | Digital Designer | Musician | Pizza
sitename: Victor Wissink
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
  - blogs
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
